/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caculator.swing;

/**
 *
 * @author ADMIN
 */
public class CalcuFrame extends javax.swing.JFrame {

    /**
     * Creates new form CalcuFrame
     */
    public CalcuFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tittle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnsqrt = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnnumber7 = new javax.swing.JButton();
        btnnumber8 = new javax.swing.JButton();
        btnnumber9 = new javax.swing.JButton();
        btndel = new javax.swing.JButton();
        btnac = new javax.swing.JButton();
        btnnumber4 = new javax.swing.JButton();
        btnnumber5 = new javax.swing.JButton();
        btnnumber6 = new javax.swing.JButton();
        btnmultiply = new javax.swing.JButton();
        btndivide = new javax.swing.JButton();
        btnnumber1 = new javax.swing.JButton();
        btnnumber2 = new javax.swing.JButton();
        btnnumber3 = new javax.swing.JButton();
        btnplus = new javax.swing.JButton();
        btnminus = new javax.swing.JButton();
        btnnumber0 = new javax.swing.JButton();
        btndot = new javax.swing.JButton();
        btnexp = new javax.swing.JButton();
        btnanswer = new javax.swing.JButton();
        btnequal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");

        tittle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tittle.setText("CASIO FAKE");

        jTextField1.setText("ManHinh");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jPanel3.setLayout(new java.awt.GridLayout(3, 6, 5, 5));

        jButton1.setText("ab/c");
        jPanel3.add(jButton1);

        btnsqrt.setText("√");
        jPanel3.add(btnsqrt);

        jButton4.setText("x2");
        jPanel3.add(jButton4);

        jButton7.setText("⋀");
        jPanel3.add(jButton7);

        jButton6.setText("log");
        jPanel3.add(jButton6);

        jButton10.setText("ln");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton10);

        jButton9.setText("(-)");
        jPanel3.add(jButton9);

        jButton12.setText("˚’ ”");
        jPanel3.add(jButton12);

        jButton8.setText("hyp");
        jPanel3.add(jButton8);

        jButton3.setText("sin");
        jPanel3.add(jButton3);

        jButton5.setText("cos");
        jPanel3.add(jButton5);

        jButton17.setText("tan");
        jPanel3.add(jButton17);

        jButton13.setText("RCL");
        jPanel3.add(jButton13);

        jButton11.setText("ENG");
        jPanel3.add(jButton11);

        jButton16.setText("(");
        jPanel3.add(jButton16);

        jButton15.setText(")");
        jPanel3.add(jButton15);

        jButton14.setText(",");
        jPanel3.add(jButton14);

        jButton18.setText("M+");
        jPanel3.add(jButton18);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1)
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setLayout(new java.awt.GridLayout(4, 5, 5, 5));

        btnnumber7.setText("7");
        jPanel4.add(btnnumber7);

        btnnumber8.setText("8");
        jPanel4.add(btnnumber8);

        btnnumber9.setText("9");
        jPanel4.add(btnnumber9);

        btndel.setBackground(new java.awt.Color(255, 77, 77));
        btndel.setForeground(new java.awt.Color(242, 242, 242));
        btndel.setText("DEL");
        btndel.setToolTipText("");
        jPanel4.add(btndel);

        btnac.setBackground(new java.awt.Color(255, 77, 77));
        btnac.setForeground(new java.awt.Color(242, 242, 242));
        btnac.setText("AC");
        jPanel4.add(btnac);

        btnnumber4.setText("4");
        jPanel4.add(btnnumber4);

        btnnumber5.setText("5");
        jPanel4.add(btnnumber5);

        btnnumber6.setText("6");
        jPanel4.add(btnnumber6);

        btnmultiply.setText("*");
        jPanel4.add(btnmultiply);

        btndivide.setText("/");
        jPanel4.add(btndivide);

        btnnumber1.setText("1");
        jPanel4.add(btnnumber1);

        btnnumber2.setText("2");
        jPanel4.add(btnnumber2);

        btnnumber3.setText("3");
        jPanel4.add(btnnumber3);

        btnplus.setText("+");
        jPanel4.add(btnplus);

        btnminus.setText("-");
        btnminus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnminusActionPerformed(evt);
            }
        });
        jPanel4.add(btnminus);

        btnnumber0.setText("0");
        jPanel4.add(btnnumber0);

        btndot.setText(".");
        jPanel4.add(btndot);

        btnexp.setText("Exp");
        jPanel4.add(btnexp);

        btnanswer.setText("Ans");
        jPanel4.add(btnanswer);

        btnequal.setText("=");
        jPanel4.add(btnequal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tittle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(tittle, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnminusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnminusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnminusActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalcuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalcuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalcuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalcuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new CalcuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnac;
    private javax.swing.JButton btnanswer;
    private javax.swing.JButton btndel;
    private javax.swing.JButton btndivide;
    private javax.swing.JButton btndot;
    private javax.swing.JButton btnequal;
    private javax.swing.JButton btnexp;
    private javax.swing.JButton btnminus;
    private javax.swing.JButton btnmultiply;
    private javax.swing.JButton btnnumber0;
    private javax.swing.JButton btnnumber1;
    private javax.swing.JButton btnnumber2;
    private javax.swing.JButton btnnumber3;
    private javax.swing.JButton btnnumber4;
    private javax.swing.JButton btnnumber5;
    private javax.swing.JButton btnnumber6;
    private javax.swing.JButton btnnumber7;
    private javax.swing.JButton btnnumber8;
    private javax.swing.JButton btnnumber9;
    private javax.swing.JButton btnplus;
    private javax.swing.JButton btnsqrt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel tittle;
    // End of variables declaration//GEN-END:variables
}
